# Generated by Django 3.2.4 on 2021-06-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphfunc',
            name='graphic',
            field=models.ImageField(editable=False, upload_to=''),
        ),
    ]
